# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00f5df058bb5b949494859d810dea8bc6f89b91f061c3b6dc3921ffc1a06b1ccd08f6450f4577aca295224fff7378e4cc09b77c051e03b5b27c53971ea30d148

test:
  secret_key_base: 866e4e3a67de7e824070f6d931c10aaf471d6c13e6d18bb137c6c78111ff3b6144f595ffff50d3ecd3eb7518d732236da5872f0e2d1d5670c8e10b3cccaa265d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
